# Generated by Django 4.1.4 on 2023-10-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
