# Generated by Django 4.2.6 on 2023-11-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_profesor_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_la_tarea', models.CharField(max_length=30)),
                ('materia', models.CharField(max_length=30)),
                ('fecha_de_entrega', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='apellidade',
            new_name='apellido',
        ),
    ]
